// axios fetch data state
export const FETCHING_RESOURCES_DONE = 'API/FETCHING_RESOURCES_DONE'
export const FETCHING_RESOURCES_FAIL = 'API/FETCHING_RESOURCES_FAIL'
export const FETCHING_RESOURCES = 'API/FETCHING_RESOURCES'
// app
export const SET_INITIAL_STATE = 'APP/SET_INITIAL_STATE'
// drawer
export const SET_DRAWER = 'DRAWER/SET_DRAWER'
export const SET_MINI_DRAWER = 'DRAWER/SET_MINI_DRAWER'
// notify
export const NOTIFY_INSTANCE = 'NOTIFY/INSTANCE'
export const NOTIFY_TIME = 'NOTIFY/TIME'
export const NOTIFY_TEXT = 'NOTIFY/TEXT'
export const NOTIFY_COLOR = 'NOTIFY/COLOR'
// delete message
export const SET_DELETE_SHOW = 'DELETE_MESSAGE/SET_DELETE_SHOW'
export const SET_DELETE_TITLE = 'DELETE_MESSAGE/SET_DELETE_TITLE'
export const SET_DELETE_NAME = 'DELETE_MESSAGE/SET_DELETE_NAME'
export const SET_DELETE_CALLBACK = 'DELETE_MESSAGE/SET_DELETE_CALLBACK'
// position
export const SET_POSITION = 'POSITION/SET_POSITION'
export const REMOVE_POSITION = 'POSITION/REMOVE_POSITION'
// auth
export const SET_LOGGED = 'AUTH/SET_LOGGED'
export const SET_PROFILE = 'AUTH/SET_PROFILE'
// breadcrumb
export const SET_BREADCRUMB = 'BREADCRUMB/SET_BREADCRUMB'
// data views
export const SET_DATA_VIEW = 'DATA_VIEW/SET_DATA_VIEW'
export const UPDATE_DATA_VIEW_ENTRY = 'DATA_VIEW/UPDATE_DATA_VIEW_ENTRY'
export const REMOVE_DATA_VIEW_ENTRY = 'DATA_VIEW/REMOVE_DATA_VIEW_ENTRY'
// user
export const SET_USERS = 'USER/SET_USERS'
export const SET_USER = 'USER/SET_USER'
// contracts
export const SET_CONTRACTS = 'CONTRACTS/SET_CONTRACTS'
// city
export const SET_CITIES = 'DATA_RAW/SET_CITIES'
export const SET_DISTRICTS = 'DATA_RAW/SET_DISTRICTS'
// setting
export const SET_SETTINGS = 'SETTING/SET_SETTINGS'
export const REMOVE_SETTING = 'SETTING/DELETE_SETTING'
export const SET_SETTING = 'SETTING/SET_SETTING'
// permission
export const SET_PERMISSION = 'PERMISSION/REMOVE_SETTING'
export const SET_ALL_PERMISSION = 'PERMISSION/SET_ALL_PERMISSION'
// role
export const SET_ROLE = 'USER/SET_ROLE'
// department
export const SET_DEPARTMENT = 'DEPARTMENT/SET_DEPARTMENT'
/// branch
export const SET_BRANCH = 'BRANCH/SET_BRANCH'
export const SET_BRANCHS = 'BRANCH/SET_BRANCHS'
/// / plan
export const SET_PLAN = 'PLAN/SET_PLAN'
// canditate
export const SET_CANDIDATE = 'CANDIDATE/SET_CANDIDATE'
